
apiVersion: v1
kind: Secret
metadata:
    name: sql-secret
type: Opaque
data:
    sql-db-name: QnVja2V0TGlzdA==
    sql-root-password: d2hhdGV2ZXI=
    sql-user-name: Zmxhc2tfYXBw
    sql-user-password: d2hhdGV2ZXI=

