apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: my-app
        image: 699819973233.dkr.ecr.us-east-1.amazonaws.com/sprint:1 
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  replicas: 1  # You can adjust the number of replicas as needed.
  serviceName: mysql-service
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: init-query
        configMap:
          name: sql-config-file 
      - name: data-volume
        persistentVolumeClaim:
          claimName: mysql-pvc  
      containers:
        - name: mysql-container
          image: mysql:5.7  
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: whatever
            - name: MYSQL_DATABASE
              value: BucketList
            - name: MYSQL_USER
              value: flask_app
            - name: MYSQL_PASSWORD
              value: whatever      
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/mysql
            - name: init-query
              mountPath: /docker-entrypoint-initdb.d/              
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql  
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
---