
pipeline { 
    agent any
    stages {
        stage('docker login and push image') {
            steps {
                withAWS(credentials: 'aws_cren', region: 'us-east-1') {
                    sh 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 699819973233.dkr.ecr.us-east-1.amazonaws.com/sprint'
                    sh 'docker build -t 699819973233.dkr.ecr.us-east-1.amazonaws.com/sprint:1 .'
                    sh 'docker push 699819973233.dkr.ecr.us-east-1.amazonaws.com/sprint:1'
                }
            }
        }
        stage('k8s') {
            steps {
                withAWS(credentials: 'aws_cren', region: 'us-east-1') {
                    sh 'aws eks update-kubeconfig --region us-east-1 --name sprint'
                    sh 'kubectl get nodes'
                }
    }
    }
}
}















