name: backend ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
            
      - name: Login to azure Registry
        uses: docker/login-action@v3
        with:
          registry: mandark.azurecr.io
          username: ${{ secrets.azure_repo_admin }}
          password: ${{ secrets.repo_password }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: /MySQL-and-Python
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            user/app:1.0
      
      - name: Push image to GHCR
        run: |
          docker buildx imagetools create \
            --tag mandark.azurecr/user/app:1.0 \
            
