name: backend ci
env:
  AZURE_WEBAPP_NAME: mn                 # set this to the name of your Azure Web App
  REPO_SERVER_NAME: mandark.azurecr.io
  image_name: backend
on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: working dir
        run: ls     
      - name: Login to azure Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REPO_SERVER_NAME }}
          username: ${{ secrets.azure_repo_admin }}
          password: ${{ secrets.repo_password }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./MySQL-and-Python/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REPO_SERVER_NAME }}/${{ env.image_name }}:lastest

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ env.REPO_SERVER_NAME }}/${{ env.image_name }}:lastest' 

